

var settingsLang = {
     moduleShortcutText: 'Настройки'
    ,moduleShortcutToolTip: '<b>Настройки<\/b><br \/>Здесь вы можете управлять типами данных и обработкой загружаемых файлов'
    ,titleMainWindow : 'Настройки'
    ,tabTitleSite : 'Сайт'
    ,tabTitleFolder : 'Справочник'
    ,tabTitleFile : 'Файл'
    ,tabTitleFiles : 'Файлы'
    ,tabTitleAccess : 'Доступ'
    ,tabTitleGeneral : 'Общие'
    ,tabTitleFlags : 'Флаги'
    ,tabTitleOptions : 'Опции'
    ,tabTitleTitle : 'Заголовок'
    ,tabTitleLocalization : 'Локализация'
    ,tabTitleAddToDir : 'Добавить категорию в'
    ,tabTitleDirProperties : 'Свойства категории'
    ,tabTitleNoName : 'Без имени'

    ,tabButtonAdd : 'Добавить'
    ,tabButtonAddToolTip : 'Добавить элемент'
    ,tabButtonDel : 'Удалить'
    ,tabButtonDelToolTip : 'Удалить выбраные элементы'
    ,tabButtonRefresh : 'Обновить'
    ,tabButtonRefreshToolTip : 'Обновить список'
    ,tabButtonCopy : 'Копировать'
    ,tabButtonCopyToolTip : 'Копировать'

    ,treeButtonExpandToolTip : 'Развернуть все'
    ,treeButtonCollapseToolTip : 'Свернуть все'
    ,treeButtonRefreshToolTip : 'Обновить дерево'
    ,treeRootNodeAlias : 'Справочники'

    ,dlgTitleDeleteItem : 'Удаление элементов'
    ,dlgTitleAddItemTo : 'Добавить элемент в'
    ,dlgMsgDeleteItem : 'Удалить выбраные элементы?'
    ,dlgMsgSaving : 'Сохранение...'
    ,dlgMsgNoTopics : 'Нет записей'
    ,dlgMsgNoFileType : 'Невыбран тип файла'
    ,dlgMsgNoFile : 'Невыбран тип файла'
    ,dlgMsgTopics : 'Записи {0} - {1} из {2}'
    ,dlgMsgLoading : 'Загрузка...'
    ,dlgMsgAfterPage : 'из {0}'
    ,dlgMsgBeforePage: 'Страница'
    ,dlgMsgFirstText: 'Первая страница'
    ,dlgMsgLastText: 'Последняя страница'
    ,dlgMsgNextText: 'Следующая страница'
    ,dlgMsgPrevText: 'Предыдущая страница'
    ,dlgMsgRefreshText: 'Обновить'

    ,labelName : 'Имя'
    ,labelAlias : 'Обозначение'
    ,labelURL : 'URL'
    ,labelTitle : 'Заголовок'
    ,labelID : 'Код'
    ,labelOrdering : 'Сортировка'
    ,labelDirectory : 'Категория'
    ,labelInserted : 'Создан'
    ,labelUpdated : 'Обновлен'
    ,labelType : 'Тип'
    ,labelDelete : 'Удалить'
    ,labelAdd : 'Добавить'
    ,labelRefresh : 'Обновить'
    ,labelProperties : 'Свойства'
    ,labelParent : 'В категории'
    ,labelHandler : 'Обработчик'
    ,labelSite : 'Сайт'
    ,labelFile : 'Файл'
    ,labelFields : 'Поля'
    ,labelFieldsValues : 'Поля - Значения'
    ,labelOwner : 'Владелец'
    ,labelSize : 'Размер'
    ,labelFrom : 'Из'
    ,labelStructure : 'Структура'


    ,formButtonSave : 'Сохранить'
    ,formButtonCancel : 'Отменить'
    ,formButtonRefresh : 'Обновить'
    ,formButtonEditorOn : 'Включить редактор'
    ,formButtonEditorOff : 'Выключить редактор'

    ,errorFailure : 'Ошибка'

    ,settings_item_view : 'Просмотр элемента'
    ,settings_item_add : 'Добавление элемента'
    ,settings_item_update : 'Редактирование элемента'
    ,settings_item_delete : 'Удаление элемента'
    ,settings_category_view : 'Просмотр категории'
    ,settings_category_add : 'Добавление категории'
    ,settings_category_update : 'Редактирование категории'
    ,settings_category_delete : 'Удаление категории'
    ,settings_field_view : 'Просмотр поля'
    ,settings_field_add : 'Добавление поля'
    ,settings_field_update : 'Редактирование поля'
    ,settings_field_delete : 'Удаление поля'

    ,HIDDEN : 'Скрыт'
    ,LOCKED : 'Фиксировать'
    ,LOG : 'Вести журнал'
    ,MENU : 'Элемент меню'
    ,REGISTER_HISTORY : 'Регистр накопления'
    ,REGISTER_STATE : 'Регистр состояния'
    ,SYSTEM : 'Системный'
    ,UPDATED : 'Обновлен'
}

